
<cumulus-deployment-name>:
  stackName: <prefix>-cumulus
  stackNameNoDash: <Prefix>Cumulus

  apiStage: dev

  vpc:
    vpcId: <vpc-id>
    subnets:
      - <subnet-id>

  ecs:
    instanceType: t2.micro
    desiredInstances: 0
    availabilityZone: <subnet-id-zone>

  buckets:
    internal: 
      name: <prefix>-internal
      type: internal
    private: 
      name: <prefix>-private
      type: private
    protected: 
      name: <prefix>-protected
      type: protected
    public: 
      name: <prefix>-public
      type: public

  iams:
    ecsRoleArn: arn:aws:iam::<aws-account-id>:role/<iams-prefix>-ecs
    lambdaApiGatewayRoleArn: arn:aws:iam::<aws-account-id>:role/<iams-prefix>-lambda-api-gateway
    lambdaProcessingRoleArn: arn:aws:iam::<aws-account-id>:role/<iams-prefix>-lambda-processing
    stepRoleArn: arn:aws:iam::<aws-account-id>:role/<iams-prefix>-steprole
    instanceProfile: arn:aws:iam::<aws-account-id>:instance-profile/<iams-prefix>-ecs
    distributionRoleArn: 'arn:aws:iam::<aws-account-id>:role/{{stackName}}-distribution-api-lambda'
    scalingRoleArn: 'arn:aws:iam::<aws-account-id>:role/{{stackName}}-scaling-role'

  urs_url: https://uat.urs.earthdata.nasa.gov/ #make sure to include the trailing slash

  # if not specified the value of the apigateway backend endpoint is used
  # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

  # if not specified the value of the apigateway dist url is used
  # api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  # URS users who should have access to the dashboard application.
  users:
    - username: <user>
    - username: <user2>
